Working version 1.0
Aftershokx/java-explore-with-me pull request #2
Opened 2022-11-06 15:49 UTC by Aftershokx

2022-11-08 17:42 UTC, alexache requested changes

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/controller/EventPrivateController.java
> +    List<EventShortDto> getCurrentUserEvents(@PathVariable long userId,
Модификатор доступа

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/controller/EventPublicController.java
> +    List<EventShortDto> getEvents(@RequestParam(required = false) String text,
Не хватает модификатора доступа

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/dto/CompilationRequestDto.java
> +    private String title;
Можно бы добавлять в эти ДТО какие-нибудь валидации

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Category.java
> +    public boolean equals(Object o) {
Действительно ли где-то требуется определение этих методов для модели? Вопрос корректного написания equals/hashcode для модели JPA не так прост. Лучше избегать их написания, если нет острой необходимости

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Compilation.java
> +        return pinned == that.pinned && id.equals(that.id) && Objects.equals(events, that.events) && title
Такой же комментарий про equals/hashcode у моделей

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Event.java
> +    public boolean equals(Object o) {
Такой же комментарий про equals/hashcode у моделей

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Location.java
> +    public boolean equals(Object o) {
Такой же комментарий про equals/hashcode у моделей

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Participation.java
> +    public boolean equals(Object o) {
Такой же комментарий про equals/hashcode у моделей

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/User.java
> +    public boolean equals(Object o) {
Такой же комментарий про equals/hashcode у моделей

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/CategoryService.java
> +        if (categoryRepository.findById(catId).isPresent()) {
Всегда можно написать .findById().orElseThrow(() -> new ObjectNotFoundException("")) и это будет правильнее с точки зрения использования Optional

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/CompilationService.java
> +        if (compilation.getEvents().contains(event)) {
Чтобы не использовался метод equals(), достаточно отфильтровывать по event Id, его уникальность должна гарантироваться - что-то вроде removeIf(e -> eventId.equals(e.getId())) или метод equals у модели определить через сравнение только по Id

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                LocalDateTime.of(2020, 9, 1, 0, 0),
Немного магическая дата

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                .map(this::setConfirmedRequestsAndViewsEventShortDto)
Очень плохо иметь запросы к БД в цикле, это можно сделать одним запросом по всем найденным событиям

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                    .filter(eventShortDto -> eventShortDto.getConfirmedRequests()
Разве не было этой информации в оригинальном списке событий из бахы выше? Зачем новый запрос к базе в цикле?

2022-11-08 17:42 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        participation.setStatus(StatusRequest.CONFIRMED);
Можно еще проверить, превышен ли теперь лимит, и тогда отменить все в очереди

2022-11-09 05:08 UTC, Aftershokx commented on docker-compose.yml
> +      - ewm-db
fixed

2022-11-09 05:17 UTC, Aftershokx commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +                start, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
fixed

2022-11-09 07:43 UTC, Aftershokx commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +            List<HitModel> models = hitRepository.findAllByUriAndTimestampBetween(uri, startDate, endDate);
fixed

2022-11-09 07:43 UTC, Aftershokx commented on stats_server/src/main/java/ru/practicum/stats_server/service/HitService.java
> +            if (Boolean.TRUE.equals(unique)) {
fixed

2022-11-09 07:48 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/controller/CategoryController.java
> +    List<CategoryResponseDto> getCategories(@RequestParam(defaultValue = "0") int from,
fixed

2022-11-09 07:48 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/controller/CompilationPublicController.java
> +    List<CompilationResponseDto> getCompilations(@RequestParam(defaultValue = "false") Boolean pinned,
fixed

2022-11-09 07:48 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/controller/EventPrivateController.java
> +    List<EventShortDto> getCurrentUserEvents(@PathVariable long userId,
fixed

2022-11-09 07:48 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/controller/EventPublicController.java
> +    List<EventShortDto> getEvents(@RequestParam(required = false) String text,
fixed

2022-11-09 07:56 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/mapper/EventMapper.java
> +                .eventDate(event.getEventDate().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")))
fixed

2022-11-09 07:56 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/Category.java
> +    public boolean equals(Object o) {
fixed

2022-11-09 07:56 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/Compilation.java
> +        return pinned == that.pinned && id.equals(that.id) && Objects.equals(events, that.events) && title
fixed

2022-11-09 08:04 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/Event.java
> +    public boolean equals(Object o) {
fixed

2022-11-09 08:05 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/Location.java
> +    public boolean equals(Object o) {
fixed

2022-11-09 08:05 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/Participation.java
> +    public boolean equals(Object o) {
fixed

2022-11-09 08:05 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/model/User.java
> +    public boolean equals(Object o) {
fixed

2022-11-09 08:07 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/CategoryService.java
> +        if (categoryRepository.findById(catId).isPresent()) {
fixed

2022-11-09 08:10 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/CompilationService.java
> +        if (compilation.getEvents().contains(event)) {
fixed

2022-11-09 08:25 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                LocalDateTime.of(2020, 9, 1, 0, 0),
fixed

2022-11-09 13:54 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                .map(this::setConfirmedRequestsAndViewsEventShortDto)
fixed

2022-11-09 13:54 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +                    .filter(eventShortDto -> eventShortDto.getConfirmedRequests()
fixed

2022-11-09 14:09 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        participation.setStatus(StatusRequest.CONFIRMED);
fixed

2022-11-09 15:00 UTC, Aftershokx commented on stats_server/src/main/java/ru/practicum/stats_server/dto/EndpointHit.java
> +    private String app;
fixed

2022-11-09 15:00 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/dto/CompilationRequestDto.java
> +    private String title;
fixed

2022-11-10 06:48 UTC, Aftershokx commented on stats_server/src/main/java/ru/practicum/stats_server/model/HitModel.java
> +@Data
fixed

2022-11-10 21:50 UTC, alexache requested changes

2022-11-10 21:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        event.setViews(event.getViews() + 1);
Раньше было лучше. Такой подход чреват высокой вероятностью ошибок. Количество просмотров должно получаться из сервиса статистики, а не быть простым ненадежным счетчиком. К тому же, обновление события админом не считается просмотром как таковым

2022-11-10 21:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        event.setConfirmedReq(event.getConfirmedReq() + 1);
Это тоже плохой способ, раньше было лучше. Все эти счетчики не будут некорректно работать, если будут параллельные запросы

2022-11-11 05:21 UTC, Aftershokx commented on docker-compose.yml
> +      - stats-db
fixed

2022-11-11 09:52 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +        event.setViews(event.getViews() + 1);
fixed

2022-11-11 09:52 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        event.setConfirmedReq(event.getConfirmedReq() + 1);
fixed

2022-11-12 18:32 UTC, alexache approved these changes

2022-11-12 18:32 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/ParticipationService.java
> +        if (participation.getStatus().equals(StatusRequest.CONFIRMED)) {
Для чего хранить это поле у события, если уже используется countDistinctByEventAndStatus ?

2022-11-12 18:32 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +            return Long.parseLong(result.substring(result.indexOf("hits=") + 5, result.indexOf("}")));
Отчего так сложно? Почему полноценно не десериализовывать ответ, как в прошлых заданиях?

2022-11-13 05:55 UTC, Aftershokx commented on main_server/src/main/java/ru/practicum/main_server/service/EventService.java
> +            return Long.parseLong(result.substring(result.indexOf("hits=") + 5, result.indexOf("}")));
Не получается так сделать на прямую, как я понял, символы "/" в /events/ все время выбивают ошибку

2022-11-13 05:58 UTC, merged